name: adroit_flutter
description: adroit
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  http: ^0.13.4
  dio: ^4.0.0
  url_launcher: ^6.0.10
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  meta: ^1.7.0
  flutter_bloc: ^7.3.1
  connectivity: ^3.0.6
  permission_handler: 8.2.5
  dartz: ^0.10.0
  get_it: ^7.2.0
  retrofit: ^2.0.1
  pretty_dio_logger: ^1.1.1
  fluttertoast: ^8.0.8
  firebase_remote_config: ^0.11.0
  flutter_svg: ^0.23.0+1
  material_floating_search_bar: ^0.3.4
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.1.0
  string_utils: ^0.2.3
  flutter_screenutil: ^5.0.0+2
  jiffy: ^4.1.0
  uuid: ^3.0.5
  extended_nested_scroll_view: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2
  build_runner: ^2.1.4
  hive_generator: ^1.1.1
  retrofit_generator: ^2.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/config/dev/
    - assets/config/prod/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf